name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build ứng dụng
      - name: Build application
        run: npm run deploy

      # 5. Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
